/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.unindra.kkp_kelompok4.cashier;

import java.awt.Color;

/**
 *
 * @author ripal
 */
public class Cashier extends javax.swing.JPanel {

    /**
     * Creates new form Cashier
     */
    public Cashier() {
        initComponents();
        Colorheader();
//        tfItem.setText("Masukan Kode Barang atau Nama Barang");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        addPanel = new javax.swing.JPanel();
        tfItem = new javax.swing.JTextField();
        btAdd = new javax.swing.JLabel();
        sumPanel = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Seperate = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Seperate1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Seperate2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Seperate3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Seperate4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListItem = new javax.swing.JTable();
        PaymentPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addPanel.setBackground(new java.awt.Color(255, 255, 255));

        tfItem.setForeground(new java.awt.Color(102, 102, 102));
        tfItem.setText("Masukan Kode Barang atau Nama Barang");
        tfItem.setToolTipText("");
        tfItem.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 255)));
        tfItem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfItemFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfItemFocusLost(evt);
            }
        });
        tfItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfItemActionPerformed(evt);
            }
        });

        btAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/unindra/kkp_kelompok4/resource/image/CashierApp/AddIcon.png"))); // NOI18N
        btAdd.setText("Tambahkan Item");

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAdd)
                    .addComponent(tfItem, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(btAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfItem, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        MainPanel.add(addPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 120));

        sumPanel.setBackground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout sumPanelLayout = new javax.swing.GroupLayout(sumPanel);
        sumPanel.setLayout(sumPanelLayout);
        sumPanelLayout.setHorizontalGroup(
            sumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        sumPanelLayout.setVerticalGroup(
            sumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        MainPanel.add(sumPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, -1, 120));

        buttonPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/unindra/kkp_kelompok4/resource/image/CashierApp/NewTransation.png"))); // NOI18N
        jLabel2.setText("New Transaction");

        Seperate.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        Seperate.setText("|");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/unindra/kkp_kelompok4/resource/image/CashierApp/OpenTransaction.png"))); // NOI18N
        jLabel3.setText("Open Transaction");

        Seperate1.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        Seperate1.setText("|");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/unindra/kkp_kelompok4/resource/image/CashierApp/Save.png"))); // NOI18N
        jLabel4.setText("Save to draft");

        Seperate2.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        Seperate2.setText("|");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/unindra/kkp_kelompok4/resource/image/CashierApp/OpenDraft.png"))); // NOI18N
        jLabel5.setText("Open from Draft");

        Seperate3.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        Seperate3.setText("|");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/unindra/kkp_kelompok4/resource/image/CashierApp/About.png"))); // NOI18N
        jLabel6.setText("About App");

        Seperate4.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        Seperate4.setText("|");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/unindra/kkp_kelompok4/resource/image/CashierApp/Report.png"))); // NOI18N
        jLabel7.setText("Report Bug");

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(Seperate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Seperate2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Seperate1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Seperate3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Seperate4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Seperate)
                    .addComponent(Seperate1)
                    .addComponent(Seperate2)
                    .addComponent(Seperate3)
                    .addComponent(Seperate4))
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel5))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel6))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPanel.add(buttonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1300, 70));

        tablePanel.setBackground(new java.awt.Color(255, 255, 255));

        jtListItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtListItem);

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );

        MainPanel.add(tablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 890, 370));

        PaymentPanel.setBackground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout PaymentPanelLayout = new javax.swing.GroupLayout(PaymentPanel);
        PaymentPanel.setLayout(PaymentPanelLayout);
        PaymentPanelLayout.setHorizontalGroup(
            PaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1310, Short.MAX_VALUE)
        );
        PaymentPanelLayout.setVerticalGroup(
            PaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        MainPanel.add(PaymentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 1310, 90));

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        MainPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 190, 410, 370));

        add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));
    }// </editor-fold>//GEN-END:initComponents

    private void tfItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfItemActionPerformed

    private void tfItemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfItemFocusLost
        String itemText = tfItem.getText();
        if (itemText.equals("")){
            tfItem.setForeground(new Color(102,102,102));
            tfItem.setText("Masukan Kode Barang atau Nama Barang");
        }
    }//GEN-LAST:event_tfItemFocusLost

    private void tfItemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfItemFocusGained
        String itemText = tfItem.getText();
        if (itemText.equals("Masukan Kode Barang atau Nama Barang")){
            tfItem.setForeground(new Color(102,102,102));
            tfItem.setText("");
        }
    }//GEN-LAST:event_tfItemFocusGained

    private void Colorheader(){
        jtListItem.getTableHeader().setBackground(new Color(0,0,255));
        jtListItem.getTableHeader().setForeground(Color.WHITE);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel PaymentPanel;
    private javax.swing.JLabel Seperate;
    private javax.swing.JLabel Seperate1;
    private javax.swing.JLabel Seperate2;
    private javax.swing.JLabel Seperate3;
    private javax.swing.JLabel Seperate4;
    private javax.swing.JPanel addPanel;
    private javax.swing.JLabel btAdd;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtListItem;
    private javax.swing.JPanel sumPanel;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JTextField tfItem;
    // End of variables declaration//GEN-END:variables
}
