package Login;

import AppPackage.AnimationClass;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ripal
 */
public class FormLogin extends javax.swing.JFrame {
    AnimationClass ac = new AnimationClass();
    /**
     * Creates new form Form_Login
     */
    public FormLogin() {
        initComponents();
        sliderShow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        left = new javax.swing.JPanel();
        jlXYZ = new javax.swing.JLabel();
        jlMinimarket = new javax.swing.JLabel();
        jlLoginIcon = new javax.swing.JLabel();
        jlIconUsername = new javax.swing.JLabel();
        jlIconPassword = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        jpPassword = new javax.swing.JPasswordField();
        jbLogin = new javax.swing.JButton();
        right = new javax.swing.JPanel();
        jlClose = new javax.swing.JLabel();
        Picture1 = new javax.swing.JLabel();
        Picture2 = new javax.swing.JLabel();
        Picture3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());

        container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        left.setBackground(new java.awt.Color(0, 0, 255));
        left.setToolTipText("");
        left.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlXYZ.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jlXYZ.setForeground(new java.awt.Color(255, 255, 255));
        jlXYZ.setText("XYZ");
        left.add(jlXYZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 100, 60));

        jlMinimarket.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jlMinimarket.setForeground(new java.awt.Color(255, 255, 255));
        jlMinimarket.setText("MINIMARKET");
        left.add(jlMinimarket, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 300, 60));

        jlLoginIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/img/AvatarLogin.png"))); // NOI18N
        left.add(jlLoginIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 140, 100));

        jlIconUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/img/Password.png"))); // NOI18N
        left.add(jlIconUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 20, 20));

        jlIconPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/img/Username.png"))); // NOI18N
        left.add(jlIconPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 30, 20));

        tfUsername.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tfUsername.setForeground(new java.awt.Color(153, 153, 153));
        tfUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfUsername.setText("Username");
        tfUsername.setToolTipText("");
        tfUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        tfUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfUsernameFocusGained(evt);
            }
        });
        left.add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 190, 40));

        jpPassword.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jpPassword.setForeground(new java.awt.Color(153, 153, 153));
        jpPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jpPassword.setText("Password");
        jpPassword.setToolTipText("");
        jpPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jpPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jpPasswordFocusGained(evt);
            }
        });
        left.add(jpPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 190, 40));

        jbLogin.setBackground(new java.awt.Color(242, 242, 242));
        jbLogin.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jbLogin.setForeground(new java.awt.Color(51, 51, 51));
        jbLogin.setText("Login");
        left.add(jbLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 190, 40));

        container.add(left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        right.setBackground(new java.awt.Color(255, 255, 255));
        right.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/img/CloseButton.png"))); // NOI18N
        jlClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCloseMouseClicked(evt);
            }
        });
        right.add(jlClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        Picture1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/img/Pic1.jpg"))); // NOI18N
        right.add(Picture1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        Picture2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/img/Pic2.jpg"))); // NOI18N
        right.add(Picture2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 500, 500));

        Picture3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/img/Pic3.jpg"))); // NOI18N
        right.add(Picture3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 500, 500));

        container.add(right, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 500, 500));

        getContentPane().add(container, "card3");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private int xx,xy;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x,y;
        x=evt.getXOnScreen();
        y=evt.getYOnScreen();
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_formMouseDragged

    private void jlCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jlCloseMouseClicked

    private void tfUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUsernameFocusGained
        String username = tfUsername.getText();
        if (username.equals("Username")){
            tfUsername.setText("");
        }
    }//GEN-LAST:event_tfUsernameFocusGained

    private void jpPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpPasswordFocusGained
        String password = jpPassword.getText();
        if (jpPassword.equals("Password")){
            jpPassword.setText("");
        }
    }//GEN-LAST:event_jpPasswordFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }
    
    
    public void sliderShow(){
        new Thread(new Runnable(){
            @Override
            public void run(){
                int nb = 0;
                try {
                    while (true){
                        switch (nb) {
                            case 0:
                                Thread.sleep(3000);
                                ac.jLabelXLeft(0, -500, 12, 10, Picture1);
                                ac.jLabelXLeft(500, 0, 12, 10, Picture2);
                                ac.jLabelXLeft(1000, 500, 12, 10, Picture3);
                                nb++; 
                            case 1:
                                Thread.sleep(3000);
                                ac.jLabelXLeft(-500,-1000, 12, 10, Picture1);
                                ac.jLabelXLeft(0, -500, 12, 10, Picture2);
                                ac.jLabelXLeft(500, 0, 12, 10, Picture3);
                                nb++;
                            case 2:
                                Thread.sleep(3000);
                                ac.jLabelXRight(-1000, -500, 12, 10, Picture1);
                                ac.jLabelXRight(-500, 0, 12, 10, Picture2);
                                ac.jLabelXRight(0, 500, 12, 10, Picture3);
                                nb++;
                            case 3:
                                Thread.sleep(3000);
                                ac.jLabelXRight(-500, 0, 12, 10, Picture1);
                                ac.jLabelXRight(0, 500, 12, 10, Picture2);
                                ac.jLabelXRight(500, 1000, 12, 10, Picture3);
                                nb=0;
                        }
                    }
                } catch (Exception ex) {
                }
            }
        }).start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Picture1;
    private javax.swing.JLabel Picture2;
    private javax.swing.JLabel Picture3;
    private javax.swing.JPanel container;
    private javax.swing.JButton jbLogin;
    private javax.swing.JLabel jlClose;
    private javax.swing.JLabel jlIconPassword;
    private javax.swing.JLabel jlIconUsername;
    private javax.swing.JLabel jlLoginIcon;
    private javax.swing.JLabel jlMinimarket;
    private javax.swing.JLabel jlXYZ;
    private javax.swing.JPasswordField jpPassword;
    private javax.swing.JPanel left;
    private javax.swing.JPanel right;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
